name: Lint

on:
    push:
        branches:
            - master
            - main
    pull_request:
jobs:
    linter:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Python Linter
              uses: sunnysid3up/python-linter@master
              with:
                  source: "ascii"
                  mypy-options: "--ignore-missing-imports --show-error-codes"
                  pylint-options: "--rcfile=setup.cfg"
                  isort-options: "-w 100"
                  django: false